CREATE SCHEMA DSS_DB_V1;
DROP TABLE USERS;
CREATE TABLE DSS_DB_V1.USERS
(
    USER_ID    VARCHAR(25) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(45) NOT NULL,
    LAST_NAME  VARCHAR(45) NOT NULL,
    PASSWORD   VARCHAR(45) NOT NULL
);

SELECT * FROM DSS_DB_V1.USERS;
