-- DDL STATEMENTS
CREATE SCHEMA DSS_DB_V1;
DROP TABLE DSS_DB_V1.MOVIES;
CREATE TABLE DSS_DB_V1.MOVIES
(
    MOVIE_ID        INT not null primary key,
    IMAGE           varchar(50) not null,
    TITLE           varchar(50),
    COST            INT,
    YEAR_OF_RELEASE INT
);

-- QUERIES
SELECT * FROM DSS_DB_V1.MOVIES;

-------------
DROP TABLE DSS_DB_V1.ACTORS;
CREATE TABLE DSS_DB_V1.ACTORS
(
    ACTOR_ID        INT NOT NULL PRIMARY KEY,
    FIRST_NAME      VARCHAR(25) NOT NULL,
    LAST_NAME       VARCHAR(25) NOT NULL,
    GENDER          CHAR(1),
    AGE             INT
);

-- QUERIES
SELECT * FROM DSS_DB_V1.ACTORS;

----------------
DROP TABLE DSS_DB_V1.MOVIEACTORS;
CREATE TABLE DSS_DB_V1.MOVIEACTORS
(
    MA_ID        BIGINT NOT NULL PRIMARY KEY,
    MOVIE_ID     INT NOT NULL,
    ACTOR_ID     BIGINT NOT NULL,
    CONSTRAINT FK_ACTORS
        FOREIGN KEY (ACTOR_ID)
            REFERENCES ACTORS(ACTOR_ID),
    CONSTRAINT FK_MOVIES
        FOREIGN KEY (MOVIE_ID)
            REFERENCES MOVIES(MOVIE_ID)
);

-- QUERIES
SELECT * FROM DSS_DB_V1.MOVIEACTORS;

-----
DROP TABLE DSS_DB_V1.REVIEW;
CREATE TABLE DSS_DB_V1.REVIEW
(
    REVIEW_ID       INT NOT NULL PRIMARY KEY,
    DATE_POSTED     TIMESTAMP,
    DESCRIPTION     VARCHAR(45),
    RATING          INT,
    MOVIE_ID        INT NOT NULL,
    CONSTRAINT FK_MOVIES
        FOREIGN KEY (MOVIE_ID)
            REFERENCES MOVIES(MOVIE_ID)
);

-- QUERIES
SELECT * FROM DSS_DB_V1.REVIEW;

-----
DROP TABLE DSS_DB_V1.USERS;
CREATE TABLE DSS_DB_V1.USERS
(
    USER_ID    INT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(45) NOT NULL,
    LAST_NAME  VARCHAR(45) NOT NULL,
    PASSWORD   VARCHAR(45) NOT NULL
);


-- QUERIES
SELECT * FROM DSS_DB_V1.USERS;


